version: 1.0.0
apiVersion: v3.1.0
kind: DataContract
id: 53581432-6c55-4ba2-a65f-72344a91553a
status: active
schema:
  - name: orders
    physicalType: table
    properties:
      - logicalType: string
        physicalType: varchar
