version: 1.0.0
apiVersion: v3.0.0
kind: DataContract
id: 53581432-6c55-4ba2-a65f-72344a91553a
status: active
name: my_table
dataProduct: my_quantum
schema:
  - name: Air_Quality
    description: Air quality of the city of New York
    authoritativeDefinitions:
      - url: https://catalog.data.gov/dataset/air-quality
        type: Reference definition on Data.gov
    dataGranularityDescription: Raw records
    physicalType: table
    properties:
    - name: UniqueID
      primaryKey: true
      businessName: Unique identifier
      logicalType: number
      physicalType: int
      quality:
      - rule: minCheck
        description: This column should not contain values under 100000
        dimension: conformity
        severity: error
        businessImpact: operational
        customProperties:
          - property: min
            value: 100000
