version: 1.0.0
kind: DataContract
id: 53581432-6c55-4ba2-a65f-72344a91553a
status: active
name: my_table
dataProduct: my_quantum
apiVersion: v3.0.1
schema:
  - name: Air_Quality
    description: Air quality of the city of New York
    authoritativeDefinitions:
      - url: https://catalog.data.gov/dataset/air-quality
        type: Reference definition on Data.gov
    dataGranularityDescription: Raw records
    physicalType: table
    properties:
    - name: DataValue
      businessName: Measured value
      logicalType: number
      physicalType: float(3,2)
      quality:
      - type: library
        rule: between
        description: 'This name should contain positive values under 500'
        dimension: accuracy
        severity: error
        businessImpact: operational
        customProperties:
          - property: min
            value: 0
          - property: max
            value: 500
