version: 1.0.0
kind: DataContract
id: 53581432-6c55-4ba2-a65f-72344a91553a
status: active
name: my_table
dataProduct: my_quantum
apiVersion: v3.0.0
schema:
  - name: transactions_tbl
    description: Provides core payment metrics
    dataGranularityDescription: Aggregation on names txn_ref_dt, pmt_txn_id
    physicalType: table
    properties:
      - name: account_id
        physicalType: string
        logicalType: string
        logicalTypeOptions:
          minLength: 11
          maxLength: 11
          pattern: ACC[0-9]{8}
      - name: txn_ref_date
        physicalType: date
        logicalType: date
        logicalTypeOptions:
          minimum: "2020-01-01"
          maximum: "2021-01-01"
          format: yyyy-MM-dd
      - name: txn_timestamp
        physicalType: timestamp
        logicalType: date
        logicalTypeOptions:
          minimum: "2020-01-01 00:00:00"
          maximum: "2021-01-01 00:00:00"
          format: "yyyy-MM-dd HH:mm:ss"
      - name: amount
        physicalType: double
        logicalType: number
        logicalTypeOptions:
          minimum: 0
          format: f32
      - name: age
        physicalType: int
        logicalType: integer
        logicalTypeOptions:
          minimum: 18
          maximum: 100
          exclusiveMaximum: true
          format: i64
      - name: is_open
        physicalType: bool
        logicalType: boolean
      - name: latest_txns
        physicalType: list
        logicalType: array
        logicalTypeOptions:
          minItems: 0
          maxItems: 3
          uniqueItems: true
      - name: customer_details
        physicalType: json
        logicalType: object
        logicalTypeOptions:
          required:
            - num_children
            - date_of_birth
          maxProperties: 5
