name: Schema Diff Analysis

on:
  pull_request:
    branches: ["*"]
    paths:
      - 'schema/odcs-json-schema-*.json'

jobs:
  schema-diff:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to access previous schema files
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install jq (optional, for better JSON formatting)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Run schema diff analysis
        id: schema-diff
        run: |
          # Run the schema diff script and capture output
          bash src/script/schema-diff.sh > diff_output.txt 2>&1 || true
          
          # Read the output file and set it as an output variable
          if [ -f diff_output.txt ]; then
            echo "diff_output<<EOF" >> $GITHUB_OUTPUT
            cat diff_output.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            // Read the diff output from file
            const fs = require('fs');
            let diffOutput = '';
            
            try {
              if (fs.existsSync('diff_output.txt')) {
                diffOutput = fs.readFileSync('diff_output.txt', 'utf8').trim();
              }
            } catch (error) {
              console.log('No diff output file found or error reading file');
            }
            
            if (!diffOutput) {
              console.log('No diff output to comment');
              return;
            }
            
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: diffOutput
            });